name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Install dependencies
        run: wally install

      - name: Build Place File for Testing
        run: rojo build -o test.rbxlx

      # Replacing the old run-in-roblox installation
      - name: Install Tools
        run: npm install -g run-in-roblox

      - name: Run Real Tests
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
        run: run-in-roblox run --place-file test.rbxlx --script scripts/run_tests.lua --universe-id 1 --place-id 1

      - name: Build Final Place File
        run: rojo build -o SimpleRobloxGame.rbxlx
